[tool.ruff]
line-length = 88
# Ensure 'I' is included in the select list to enable isort rules
select = ["F", "E", "W", "I"]

[tool.ruff.isort]
lines-after-imports = 2
force-single-line = true

[tool.pytest.ini_options]
addopts = "-W ignore::DeprecationWarning"

[tool.mypy]
ignore_missing_imports = true
plugins = ["pydantic.mypy"]
exclude = [".git", "__pycache__", "docs/source/conf.py", "old", "build", "dist", "app/tests", "alembic"]

[mypy.app.tests]
ignore_errors = true
